# Generated by Django 4.0.5 on 2022-06-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saloon_no', models.CharField(max_length=10)),
                ('saloon_name', models.CharField(max_length=50)),
            ],
        ),
    ]
